config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home/top'

  root to: 'home#top'
  get 'rooms/index'
  resources :rooms
  get 'search', to: 'rooms#search'

  resources :reservations
  get 'reservations/index'
  post 'reservations/confirm'

  get 'users/show', to: 'users#show'
  get 'users/profile', to: 'users#profile'
  get 'users/profile/edit', to: 'users#profile_edit'
  patch 'users/profile/update', to: 'users#profile_update'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'profile_show', to: 'users/registrations#profile_show'
    get 'profile_edit', to: 'users/registrations#profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update'
    delete '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations

  validates :facilityname, presence: true
  validates :facilityintroduction, presence: true
  validates :address, presence: true
  validates :cost, presence: true, numericality: { greater_than_or_equal_to: 1 }

  mount_uploader :facilitypic, FacilitypicUploader

  def self.search(keyword)
    where(["facilityname like? OR facilityintroduction like?", "%#{keyword}%", "%#{keyword}%"])
  end

  def self.search_by_area(keyword)
    where(["address like?", "%#{keyword}%"])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = current_user.rooms
  end

  def new
    @room = Room.new
    @user = current_user
  end

  def create
    @user = current_user
    @room = Room.new(params.require(:room).permit(:facilityname, :facilitypic, :facilityintroduction, :cost, :address, :user_id))
    if @room.save
      redirect_to rooms_path
    else
      render new_room_path
    end
  end

  def show
    @room = Room.find(params[:id])
    @user = current_user
    @reservation = Reservation.new
  end

  def edit
  end

  def update
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_index_path
  end

  def search
    puts @subject
    if params[:subject] == "free"
      @rooms = Room.search(params[:keyword])
      @keyword = params[:keyword]
    elsif params[:subject] == "area"
      @rooms = Room.search_by_area(params[:keyword])
      @keyword = params[:keyword]
    elsif params[:subject] == "Tokyo"
      @rooms = Room.search_by_area("東京")
    elsif params[:subject] == "Osaka"
      @rooms = Room.search_by_area("大阪")
    elsif params[:subject] == "Kyoto"
      @rooms = Room.search_by_area("京都")
    elsif params[:subject] == "Sapporo"
      @rooms = Room.search_by_area("札幌")
    end
    if @rooms.count == 0
      @rooms = Room.all
    end
    render "result"
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword,:placeholder => "キーワードを入力", value: @keyword %>
    <%= f.hidden_field :subject, value: "free"  %>
    <%= f.submit "検索" %>
  <% end %>
</div>
<div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, :placeholder => "エリア名を入力",value: @keyword %>
    <%= f.hidden_field :subject, value: "area"  %>
    <%= f.submit "検索" %>
  <% end %>
<h3>登録施設一覧</h3>

  <table class="index-table">
    <thead>
      <tr>
        <th>施設名</th>
        <th>施設画像</th>
        <th>紹介文</th>
        <th>料金</th>
        <th>作成日</th>
      </tr>
    </thead>

    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.facilityname %></td>
          <td><%= image_tag room.facilitypic.url , class:"fpic", alt: "施設画像" %></td>
          <td><%= room.facilityintroduction %></td>
          <td><%= room.cost %></td>
          <td><%= l room.created_at %></td>
          <td>
              <%= link_to "詳細", room %>
          </td>
          <td>
            <%= link_to "削除",  room, method: :delete %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/rooms/new.html.erb
<h3>施設登録</h3>
<%= render "shared/error", obj: @room %>
    <%= form_with model: @room do |f| %>
      <table>
        <tr>
          <th><%= f.label :facilityname ,"施設名" %></th>
          <td><%= f.text_field :facilityname %></td>
        </tr>

        <tr>
          <th><%= f.label :facilitypic,"施設画像" %></th>
          <td><%= f.file_field :facilitypic, class: "image" %></td>
        </tr>

        <tr>
          <th><%= f.label :facilityintroduction ,"紹介文" %></th>
          <td><%= f.text_field :facilityintroduction %></td>
        </tr>

        <tr>
          <th><%= f.label :cost ,"料金" %></th>
          <td><%= f.text_field :cost %></td>
        </tr>
        <tr>
          <th><%= f.label :address ,"住所" %></th>
          <td><%= f.text_area :address %></td>
        </tr>
      </table>
      <%= f.hidden_field :user_id, value: @user.id %>
      <div>
        <ul>
          <li><%= f.submit "登録完了する"%></li>
          <li><%= link_to "施設一覧に戻る", rooms_path %></li>
        </ul>
      </div>
    <% end %>

app/views/rooms/result.html.erb
<div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword,:placeholder => "キーワードを入力", value: @keyword %>
    <%= f.hidden_field :subject, value: "free"  %>
    <%= f.submit "検索" %>
  <% end %>
</div>
<div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, :placeholder => "エリア名を入力",value: @keyword %>
    <%= f.hidden_field :subject, value: "area"  %>
    <%= f.submit "検索" %>
  <% end %>
</div>
<h3>検索結果</h3>
<p>条件に合う施設が<%= @rooms.count %>件見つかりました。</p>
  <table class="index-table">
    <thead>
      <tr>
        <th>施設名</th>
        <th>住所</th>
        <th>紹介文</th>
        <th>料金</th>
      </tr>
    </thead>

    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.facilityname %></td>
          <td><%= room.address%></td>
          <td><%= room.facilityintroduction %></td>
          <td><%= room.cost %></td>
          <td>
            <% if user_signed_in? %>
              <%= link_to "詳細", room %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/rooms/show.html.erb
<h3>施設詳細</h3>
<%= render "shared/error", obj: @reservation %>
  <table class="index-table">
    <thead>
      <tr>
        <th>施設名</th>
        <th>施設画像</th>
        <th>紹介文</th>
        <th>料金</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @room.facilityname %></td>
        <td><%= image_tag @room.facilitypic.url , class:"fpic", alt: "施設画像" %></td>
        <td><%= @room.facilityintroduction %></td>
        <td><%= @room.cost %></td>
      </tr>
    </tbody>
  </table>

  <%= form_with model: @reservation, url:  reservations_confirm_path, method: :post do |f| %>
    <table>
      <tr>
        <th><%= f.label :check_in_date ,"チェックイン日" %></th>
        <td><%= f.date_field :check_in_date %></td>
      </tr>

      <tr>
        <th><%= f.label :check_out_date ,"チェックアウト日" %></th>
        <td><%= f.date_field :check_out_date %></td>
      </tr>

      <tr>
        <th><%= f.label :people_number ,"人数" %></th>
        <td><%= f.text_field :people_number %></td>
      </tr>

    </table>
    <%= f.hidden_field :room_id, value: @room.id %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.submit "予約する"%>
  <% end %>
<%= link_to "戻る", :back %>