config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home/top'

  root to: 'home#top'
  get 'rooms/index'
  resources :rooms
  get 'search', to: 'rooms#search'

  resources :reservations
  get 'reservations/index'
  post 'reservations/confirm'

  get 'users/show', to: 'users#show'
  get 'users/profile', to: 'users#profile'
  get 'users/profile/edit', to: 'users#profile_edit'
  patch 'users/profile/update', to: 'users#profile_update'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'profile_show', to: 'users/registrations#profile_show'
    get 'profile_edit', to: 'users/registrations#profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update'
    delete '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservationapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class = "header-container" >
      <div class = "header-logo-container">
      <%= link_to image_tag("header_logo.png", class: "header-logo"),  root_path %>
      </div>
    <% if current_user.present? == true && current_user.profilepic.present? == true %>
      <div class="mypage-btn-container" id="mypageBtnContainer">
        <button class="btn-drop" >
          <div>
            <%= image_tag current_user.profilepic.url , class:"toppic", alt: "アイコン画像" %>
          </div>
          <div class = "header_name"><%= current_user.name %></div>
        </button>
        <div class="mypage-dropdown" id="mypageDropdown">
	        <ul>
	          <li><%= link_to '施設登録', new_room_path %></li>
	          <li><%= link_to '予約済み一覧', reservations_path %></li>
            <li><%= link_to '登録済み一覧', rooms_index_path %></li>
            <li><%= link_to 'アカウント設定', profile_show_path %></li>
            <li><%= link_to 'プロフィール', users_profile_path %></li>
	          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
	        </ul>
        </div>
      </div>
    <% elsif current_user.present? == true && current_user.profilepic.present? == false %>
      <div class="mypage-btn-container" id="mypageBtnContainer">
        <button class="btn-drop" >
          <%= image_tag "prof_default.png", class:"toppic" %>
          <p class = "header_name"><%= current_user.name %></p>
        </button>
        <div class="mypage-dropdown" id="mypageDropdown">
	        <ul>
	          <li><%= link_to '施設登録', new_room_path %></li>
	          <li><%= link_to '予約済み一覧', reservations_path %></li>
            <li><%= link_to '登録済み一覧', rooms_index_path %></li>
            <li><%= link_to 'アカウント設定', profile_show_path %></li>
            <li><%= link_to 'プロフィール', users_profile_path %></li>
	          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
	        </ul>
        </div>
      </div>
    <% elsif current_user.present? == false %>
      <div>
        <%= button_to '新規登録', {controller: 'users/registrations', action: 'new'}, {method: :get }%>
        <%= button_to 'ログイン', {controller: 'users/sessions', action: 'new'}, {method: :get }%>
      </div>
    <% end %>
  </div>

    <%= yield %>
    <div class = "header-logo-container">
      <%= link_to image_tag("header_logo.png", class: "header-logo"),  root_path %>
    </div>
  </body>
</html>